export const COL = {
  clubs: "clubs",
  clubsLegacy: "Kulüpler",
  clubPosts: "club_posts",
  clubPostsLegacy: "KulüpPaylasimlari",
  clubApplications: "club_applications",
  clubApplicationsLegacy: "KulüpBaşvuruları",
  clubMembers: "club_members",
  clubMembersLegacy: "KulüpÜyeleri",
  checkins: "checkins",
  checkinsLegacy: "Check-in",
  rsvps: "rsvps",
  rsvpsLegacy: "RSVP'ler",
  events: "events",
  eventsLegacy: "Etkinlikler",
  users: "users",
  usersLegacy: "Kullanıcılar",
  sessions: "sessions",
};
