// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKECXgO6viL1Br9TJLjZicP-RdRNENczs',
    appId: '1:1004091237817:web:3db01a17c14509fc85c268',
    messagingSenderId: '1004091237817',
    projectId: 'eventmint-560e0',
    authDomain: 'eventmint-560e0.firebaseapp.com',
    databaseURL: 'https://eventmint-560e0-default-rtdb.firebaseio.com',
    storageBucket: 'eventmint-560e0.firebasestorage.app',
    measurementId: 'G-C9W312MWKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1J-lIscfQnAcXYMF9GymLiCdigY0vKng',
    appId: '1:1004091237817:android:990b9a325a537fbd85c268',
    messagingSenderId: '1004091237817',
    projectId: 'eventmint-560e0',
    databaseURL: 'https://eventmint-560e0-default-rtdb.firebaseio.com',
    storageBucket: 'eventmint-560e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNR9ze4k65l_x2Uq-lr8cI6i0n9QMR2WE',
    appId: '1:1004091237817:ios:4484a627e5f16de185c268',
    messagingSenderId: '1004091237817',
    projectId: 'eventmint-560e0',
    databaseURL: 'https://eventmint-560e0-default-rtdb.firebaseio.com',
    storageBucket: 'eventmint-560e0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNR9ze4k65l_x2Uq-lr8cI6i0n9QMR2WE',
    appId: '1:1004091237817:ios:4484a627e5f16de185c268',
    messagingSenderId: '1004091237817',
    projectId: 'eventmint-560e0',
    databaseURL: 'https://eventmint-560e0-default-rtdb.firebaseio.com',
    storageBucket: 'eventmint-560e0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKECXgO6viL1Br9TJLjZicP-RdRNENczs',
    appId: '1:1004091237817:web:15e7312e0e5ec3c485c268',
    messagingSenderId: '1004091237817',
    projectId: 'eventmint-560e0',
    authDomain: 'eventmint-560e0.firebaseapp.com',
    databaseURL: 'https://eventmint-560e0-default-rtdb.firebaseio.com',
    storageBucket: 'eventmint-560e0.firebasestorage.app',
    measurementId: 'G-4JR1E8JQB6',
  );
}
